# CVE-2014-2667


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2014-11-16 | 2017-07-01 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:python:python:3.3.2:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.2:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.5:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.6:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.4.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.4:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.6:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.4.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.4.2:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.4:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.5:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.3.3:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 3.3 | LOW | 4.9 | 3.4 | AV:L/AC:M/Au:N/C:P/I:P/A:N | 2.0 | LOCAL | MEDIUM | NONE | False | False | False | False | PARTIAL | PARTIAL | NONE |

## Problem Type
CWE-362

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
openSUSE-SU-2014:0597|http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html|SUSE|[]
openSUSE-SU-2014:0596|http://lists.opensuse.org/opensuse-updates/2014-05/msg00007.html|SUSE|[]
[oss-security] 20140329 Re: [PSRT] CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python|http://www.openwall.com/lists/oss-security/2014/03/29/5|MLIST|[]
[oss-security] 20140330 Re: CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python|http://www.openwall.com/lists/oss-security/2014/03/30/4|MLIST|[]
[oss-security] 20140328 CVE request: os.makedirs(exist_ok=True) is not thread-safe in Python|http://www.openwall.com/lists/oss-security/2014/03/28/15|MLIST|[]
http://bugs.python.org/issue21082|http://bugs.python.org/issue21082|CONFIRM|['Vendor Advisory']
GLSA-201503-10|https://security.gentoo.org/glsa/201503-10|GENTOO|[]
openSUSE-SU-2020:0086|http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html|SUSE|[]
