# CVE-2014-1624


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2014-01-28 00:55:00 | 2017-08-29 01:34:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:python:pyxdg:0.25:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 3.3 | LOW | 4.9 | 3.4 | AV:L/AC:M/Au:N/C:N/I:P/A:P | 2.0 | LOCAL | MEDIUM | NONE | 0 | False | False | False | NONE | PARTIAL | PARTIAL |

## Problem Type
CWE-59

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20140121 Re: Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp|http://www.openwall.com/lists/oss-security/2014/01/21/4|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247|http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247|MISC|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20140121 Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp|http://www.openwall.com/lists/oss-security/2014/01/21/3|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
65042|http://www.securityfocus.com/bid/65042|BID|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
pythonxdg-cve20141624-symlink(90618)|https://exchange.xforce.ibmcloud.com/vulnerabilities/90618|XF|[]
