# CVE-2009-5010


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2010-10-19 | 2010-10-20 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:* | []  0.5.0   | OR |
| True  cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 4.3 | MEDIUM | 2.9 | 8.6 | AV:N/AC:M/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | MEDIUM | NONE | False | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-362

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://code.google.com/p/pyftpdlib/source/detail?r=439|http://code.google.com/p/pyftpdlib/source/detail?r=439|CONFIRM|[]
https://bugs.launchpad.net/zodb/+bug/135108|https://bugs.launchpad.net/zodb/+bug/135108|MISC|[]
[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/24/3|MLIST|[]
http://code.google.com/p/pyftpdlib/issues/detail?id=91|http://code.google.com/p/pyftpdlib/issues/detail?id=91|CONFIRM|[]
http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py|http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py|CONFIRM|[]
http://bugs.python.org/issue6706|http://bugs.python.org/issue6706|MISC|['Patch']
http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY|http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY|CONFIRM|[]
[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/09/6|MLIST|[]
[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/22/3|MLIST|[]
[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/11/2|MLIST|[]
