# CVE-2006-1542


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2006-03-30 | 2017-10-19 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | "Stack-based buffer overflow in Python 2.4.2 and earlier, running on Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5, allows local users to cause a ""stack overflow,"" and possibly gain privileges, by running a script from a current working directory that has a long name, related to the realpath function.  NOTE: this might not be a vulnerability. However, the fact that it appears in a programming language interpreter could mean that some applications are affected, although attack scenarios might be limited because the attacker might already need to cross privilege boundaries to cause an exploitable program to be placed in a directory with a long name; or, depending on the method that Python uses to determine the current working directory, setuid applications might be affected." |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:python_software_foundation:python:2.2:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:* | []  2.4.2   | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.3.2:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.3.3:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.3:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.3.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.3.4:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python_software_foundation:python:2.2.1:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 3.7 | LOW | 6.4 | 1.9 | AV:L/AC:H/Au:N/C:P/I:P/A:P | 2.0 | LOCAL | HIGH | NONE | False | False | False | True | PARTIAL | PARTIAL | PARTIAL |

## Problem Type
NVD-CWE-Other

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://www.gotfault.net/research/exploit/gexp-python.py|http://www.gotfault.net/research/exploit/gexp-python.py|MISC|['Exploit']
31492|http://secunia.com/advisories/31492|SECUNIA|[]
RHSA-2008:0629|http://www.redhat.com/support/errata/RHSA-2008-0629.html|REDHAT|[]
1591|https://www.exploit-db.com/exploits/1591|EXPLOIT-DB|[]
