# CVE-2022-42969


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-10-16 | 2022-10-18 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:pytest:py:*:*:*:*:*:*:*:* | []  1.11.0   | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 3.6 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | NONE | NONE | HIGH |

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
NVD-CWE-Other

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://pypi.org/project/py|https://pypi.org/project/py|MISC|['Product', 'Third Party Advisory']
https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316|https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316|MISC|['Exploit', 'Third Party Advisory']
https://github.com/pytest-dev/py/issues/287|https://github.com/pytest-dev/py/issues/287|MISC|['Exploit', 'Issue Tracking', 'Third Party Advisory']
