# CVE-2010-3495


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2010-10-19 20:00:00 | 2011-01-22 06:43:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB) before 3.10.0 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:zope:zodb:3.9.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.8.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0b5:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:2.11.4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:2.9.11:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.8.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.5:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:2.10.9:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.6:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.4.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0b3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.7:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.1.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.8.6:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.8.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.8:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.3.3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:2.8.11:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0b4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0b1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.2.4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0c1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:*:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:zope:zodb:3.9.0b2:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 4.3 | MEDIUM | 2.9 | 8.6 | AV:N/AC:M/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | MEDIUM | NONE | 0 | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-362

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/11/2|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
41755|http://secunia.com/advisories/41755|SECUNIA|['Vendor Advisory']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://pypi.python.org/pypi/ZODB3/3.10.0#id1|http://pypi.python.org/pypi/ZODB3/3.10.0#id1|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/22/3|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/24/3|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://bugs.python.org/issue6706|http://bugs.python.org/issue6706|MISC|['Patch']
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/09/6|MLIST|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://bugs.launchpad.net/zodb/+bug/135108|https://bugs.launchpad.net/zodb/+bug/135108|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
SUSE-SR:2010:024|http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html|SUSE|[]
