# CVE-2011-4137


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2011-10-19 10:55:00 | 2018-01-18 02:29:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.5:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:0.95:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.1.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.0.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:0.91:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:0.96:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.1:2:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.0.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:0.95.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.1.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2.4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.3:alpha1:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.3:alpha2:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:djangoproject:django:1.1.3:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 5.0 | MEDIUM | 2.9 | 10.0 | AV:N/AC:L/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | LOW | NONE | 0 | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-399

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://bugzilla.redhat.com/show_bug.cgi?id=737366|https://bugzilla.redhat.com/show_bug.cgi?id=737366|CONFIRM|['Patch']
https://www.djangoproject.com/weblog/2011/sep/10/127/|https://www.djangoproject.com/weblog/2011/sep/10/127/|CONFIRM|['Patch']
[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws|http://openwall.com/lists/oss-security/2011/09/13/2|MLIST|['Patch']
[oss-security] 20110916 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws|http://openwall.com/lists/oss-security/2011/09/15/5|MLIST|[]
https://www.djangoproject.com/weblog/2011/sep/09/|https://www.djangoproject.com/weblog/2011/sep/09/|CONFIRM|['Patch', 'Vendor Advisory']
[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws|http://openwall.com/lists/oss-security/2011/09/11/1|MLIST|['Patch']
46614|http://secunia.com/advisories/46614|SECUNIA|[]
DSA-2332|http://www.debian.org/security/2011/dsa-2332|DEBIAN|[]
openSUSE-SU-2012:0653|https://hermes.opensuse.org/messages/14700881|SUSE|[]
