# CVE-2022-35983


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-09-16 22:15:00 | 2022-09-17 01:55:00 | security-advisories@github.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | TensorFlow is an open source platform for machine learning. If `Save` or `SaveSlices` is run over tensors of an unsupported `dtype`, it results in a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue. |

## Configurations
*** Not Provided ***

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-617

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4|https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4|CONFIRM|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4|https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4|MISC|[]
